### ISSUE TITLE
Accept one more option for opts to accept TARGET_HOST to execute against for all litmus functions

### ISSUE THREAD

**Issue by sheenaajay** [puppetlabs/puppet_litmus#418]
## Use Case
Accept one more option for opts to accept TARGET_HOST to execute against for all litmus functions.

So user doesn't have to add helper function in spec_helper to change target host to execute in specific nodes.
https://github.com/puppetlabs/puppetlabs-websphere_application_server/blob/main/spec/spec_helper_acceptance_local.rb#L44

## Describe the Solution You Would Like
Update the opts Hash to accept node to execute the command.
By default it will be nil. 
If value is passed then ENV['TARGET_HOST'] will be set with that node value and execute the command against it.
Old Behaviour will still be the default one. 
User will be given an option to specify the node on which they would like to execute the command.

https://github.com/puppetlabs/puppet_litmus/blob/69812a53cd44aa6e89d11cd8af367c5f56ac4dec/lib/puppet_litmus/puppet_helpers.rb#L40

Changes required for the following functions
apply_manifest
run_shell
bolt_upload_file
run_bolt_task
bolt_run_script

**Comment by RandomNoun7** [comment]
There shouldn't be a need to set a new value for the `ENV['TARGET_HOST']` environment variable. The only purpose of that variable is to [populate the value for the `target_node_name` variable](https://github.com/puppetlabs/puppet_litmus/blob/main/lib/puppet_litmus/puppet_helpers.rb#L57) before it is [passed to the BoltSpec helper](https://github.com/puppetlabs/puppet_litmus/blob/main/lib/puppet_litmus/puppet_helpers.rb#L116).

If the Litmus helper function accepts an option specifying the target name, then the value for the `target_node_name` can be used from that option directly, and the `ENV['TARGET_HOST']` variable ignored entirely.

This is important because the most significant weakness of any host targeting strategy that leverages the environment variable is that any test that targets a specific host will typically then contaminate target hosts of any call to Litmus that doesn't specifically set it's own target host. 

For example, if the Litmus helper targets the Puppet Server by affecting the value of that environment variable, then any call to a Litmus helper from then on will always target the server until someone else specifically resets that value to target agents.

As a general principle, environment variables should only be used in a context where something can be said to be true for the environment context in which a given code base is running. If someone is running a test suite wherein there is no need to target hosts specifically, then an environment variable is a valid thing to use, especially if the set of nodes to target differs from one environment to the next. But, for the purposes of passing information to a function that may need to change with any particular invocation, and the criteria for the value should be is not directly related to the environment the code is running in, then an environment variable is not a great option.
