### ISSUE TITLE
spec_helper_acceptance example is verbose

### ISSUE THREAD

**Issue by MikaelSmith** [puppetlabs/puppet_litmus#48]
If we believe the example for spec/spec_helper_acceptance.rb is a good common pattern, could that be pulled into a helper that we call?

**Comment by tphoney** [comment]
We have a ticket to move this into pdk-templates

**Comment by ekohl** [comment]
@tphoney I think that's a bad idea. You're just copying a ton of code. pdk-templates has the same problem as modulesync: you're making it easy to have a ton of boiler plate rather than designing proper libraries. In some cases this is unavoidable (Travis config) but with Ruby code we can avoid this. [puppetlabs_spec_helper](https://github.com/puppetlabs/puppetlabs_spec_helper) is a good example of avoiding this. I'd like to either see some helpers in litmus itself or in puppetlabs_spec_helper.

**Comment by tphoney** [comment]
as always, you are right @ekohl 👍 . This could just be in litmus itself, and people can override it if needs be.
My goal was to stop spec_helper_acceptance.rb to be a mess of boiler plate and customer. We could just move this as another ruby file that we load at the top of the spec_helper_acceptance.rb

**Comment by DavidS** [comment]
For internal reference, the pdk-templates ticket is FM-8300 and I created https://tickets.puppetlabs.com/browse/MODULES-10031 for the move-to-litmus part.

**Comment by ekohl** [comment]
https://github.com/puppetlabs/puppet_litmus/pull/210 is merged so now the docs need updating. Maybe this needs to wait for a release that includes it?

**Comment by michaeltlombardi** [comment]
Docs are now updated, the docs wiki is separate from the release cadence, the latest release of Litmus includes the configure method.

https://github.com/puppetlabs/puppet_litmus/wiki/Converting-a-module-to-use-Litmus#specspec_helper_acceptancerb
