### ISSUE TITLE
Allow customising module used for installing Puppet agent

### ISSUE THREAD

**Issue by danielkza** [puppetlabs/puppet_litmus#539]
## Use Case
I need to use a custom module to install puppet agents onto targets, as the operating systems I am working with don't have packages from PuppetLabs repositories at the moment.

## Describe the Solution You Would Like
Allow a way to configure some module name instead of `puppet_agent`. It doesn't even need to change the usage, as the module can still be assumed to have a task named `install`.

## Describe Alternatives You've Considered
I'm trying to hack around a custom way to provision the VMs created by `provision`, but simply pointing to a custom module would make life so much easier.

**Comment by h0tw1r3** [comment]
There's nothing that forces you to run the `litmus:install_agent` task, so roll your own 😄 
I typically handle edge cases like this by replacing the rake task with a custom one. Eg, instead of calling `rake litmus:install_agent`, `rake litmus:my_install_agent`.

You could start by coping the [litmus:install_agent](https://github.com/puppetlabs/puppet_litmus/blob/6445dd8e845bfef3267968f3e47dfb2fca9a3cc9/lib/puppet_litmus/rake_tasks.rb#L118) rake task into a custom rake file.

[This is an example](https://github.com/h0tw1r3/puppet-gitea/blob/466ab1fd77b1c8d61b9d01aaa493b0983c71c2c9/rakelib/litmus.rake#L22) of adding rake tasks to the litmus namespace.

**Comment by jordanbreen28** [comment]
Closing inline with above comment. Thanks for raising @danielkza
